import { act, renderHook, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { useHomeState } from './useHomeState.js';
import { fetchMock, socketMock, telegram } from '../test/harness.js';
const visible = value => { Object.defineProperty(document, 'visibilityState', { configurable: true, value }); document.dispatchEvent(new Event('visibilitychange')); };
afterEach(() => { visible('visible'); vi.useRealTimers(); });
const observations = socket => socket.sent.filter(frame => frame.type === 'home_observe');
it('BUG-279: Home observation starts after baseline, stops on hidden/unmount and resumes only for the current owner', async () => {
  telegram.signIn(); fetchMock.route('/api/agents', { agents: [] });
  const view = renderHook(({ observing }) => useHomeState({ wsUrl: 'ws://localhost:8765', observing }), { initialProps: { observing: true } });
  await waitFor(() => expect(view.result.current.loaded).toBe(true));
  const ws = socketMock.last(); await act(async () => ws.open());
  expect(observations(ws)).toEqual([]);
  act(() => ws.emit({ type: 'home_state', agents: [], game: null }));
  expect(observations(ws).at(-1)).toEqual({ type: 'home_observe', visible: true });
  act(() => visible('hidden'));
  expect(observations(ws).at(-1)).toEqual({ type: 'home_observe', visible: false });
  act(() => visible('visible'));
  expect(observations(ws).at(-1).visible).toBe(true);
  view.rerender({ observing: false });
  expect(observations(ws).at(-1).visible).toBe(false);
  view.rerender({ observing: true });
  expect(observations(ws).at(-1).visible).toBe(true);
  view.unmount();
  expect(ws.sent.at(-1)).toEqual({ type: 'floor_unsub' });
});
it('BUG-279: ordinary floor subscriptions do not authorize Home eating', async () => {
  telegram.signIn(); fetchMock.route('/api/agents', { agents: [] });
  const view = renderHook(() => useHomeState({ wsUrl: 'ws://localhost:8765' }));
  await waitFor(() => expect(view.result.current.loaded).toBe(true));
  const ws = socketMock.last(); await act(async () => { ws.open(); ws.emit({ type: 'home_state', agents: [], game: null }); });
  expect(observations(ws)).toEqual([]);
});
it('BUG-279: hidden heartbeats and retired owner sockets cannot authorize a later household', async () => {
  vi.useFakeTimers({ toFake: ['setInterval', 'clearInterval'] });
  fetchMock.route('/api/agents', { agents: [] });
  const view = renderHook(props => useHomeState(props), { initialProps: { wsUrl: 'ws://localhost:8765', userId: 'one', initData: 'one', observing: true } });
  const first = socketMock.last();
  await act(async () => { first.open(); first.emit({ type: 'home_state', userId: 'one', agents: [], game: null }); });
  act(() => visible('hidden'));
  const count = observations(first).length;
  await act(async () => { await vi.advanceTimersByTimeAsync(16000); });
  expect(observations(first)).toHaveLength(count);
  view.rerender({ wsUrl: 'ws://localhost:8765', userId: 'two', initData: 'two', observing: true });
  const second = socketMock.last();
  await act(async () => { second.open(); first.emit({ type: 'home_state', userId: 'one', agents: [], game: null }); });
  expect(observations(second)).toEqual([]);
  await act(async () => second.emit({ type: 'home_state', userId: 'two', agents: [], game: null }));
  expect(observations(second).at(-1)).toEqual({ type: 'home_observe', visible: false });
  act(() => visible('visible'));
  expect(observations(second).at(-1)).toEqual({ type: 'home_observe', visible: true });
  expect(observations(first)).toHaveLength(count);
});
